#!/bin/bash
if [[ -v SSH_CLIENT ]]; then
    TMPFILE=$(mktemp)
    systemctl show-environment | awk '{print "export "$0}' >> "$TMPFILE"
    source "$TMPFILE"
    rm "$TMPFILE"
fi
if [[ "$(genie -r)" != "running" ]];then
    /usr/bin/genie -i
fi
# Are we in the bottle?
if [[ ! -v INSIDE_GENIE ]]; then
    read -p "yn? * Not inside the genie bottle; enter it? " yn
    echo

    if [[ $yn == "y" ]]; then
        echo "Starting genie:"
        exec /usr/bin/genie -s
        # exec /usr/bin/genie -c tmux
    fi
else
    echo -n " * Waiting for systemd (user)..."
    until systemctl --user is-system-running &>/dev/null
    do
        sleep 1
        echo -n "."
    done
    echo
fi
