#!/bin/bash
# SSH with automatic tmux connection, fails over to normal shell if no tmux is present
# This one liner does:
# - Checks if tmux is present
# - Attachs or connnects to tmux
# - If tmux is not present, starts a normal shell
# shellcheck disable=SC2034
# host=$@
# function sshi()
# {
/usr/bin/ssh "$@" -t /bin/sh "command -v tmux &>/dev/null || tmux new -A -s $(whoami) || $SHELL -l"
# /usr/bin/ssh $host -t /bin/sh "command -v tmux &>/dev/null || tmux new -A -s $(whoami) || $SHELL -l"
# }
