#!/bin/bash
# set vi mode for bash and vim as the default editor
set -o vi

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar

## Setting powerline daemon to improve speed
powerline-daemon -q
# shellcheck disable=SC2034
POWERLINE_BASH_CONTINUATION=1
# shellcheck disable=SC2034
POWERLINE_BASH_SELECT=1

# Make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# Setting tmux to launch always on gui only or on wsl
if [[ $DISPLAY ]] || [[ "$(< /proc/sys/kernel/osrelease)" == *microsoft* ]]; then
    [[ -z "$TMUX" ]] && exec tmux
fi
# source ~/.shell_config/commands/innernet


#Enabling bash completion
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
      # shellcheck disable=SC1091
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
      # shellcheck disable=SC1091
    . /etc/bash_completion
  fi
fi

# Auto-completion
# shellcheck disable=SC1090
[[ $- == *i* ]] && source "$HOME"/.fzf/shell/completion.bash 2> /dev/null
# Key bindings
# shellcheck disable=SC1090
source "$HOME"/.fzf/shell/key-bindings.bash

# Enabling tmux completion
# shellcheck disable=SC1091 disable=1090
source "$HOME"/.tmux/completion/completions/tmux

# Enabling prompt
# shellcheck disable=SC1091 disable=1090
if [[ $USER == root ]]; then
    source "$HOME"/.shell_config/prompt/prompt-dracula.sh
else
    source "$HOME"/.shell_config/prompt/prompt-gruvbox.sh
fi

# Calling config files
# shellcheck disable=1090
for f in "$HOME"/.shell_config/myalias/*;
do
   if [ -f "$f" ]
   then
       source "$f";
   fi
done

# Terraform settings
complete -C /usr/bin/terraform terraform

# Calling evn variables
# shellcheck disable=1090
source "$HOME"/.shell_config/env
